const surnoms = [
     { arabe: "حبيبتي", transliteration: "Habibti", signification: "mon amour" },
     { arabe: "عمري", transliteration: "Omri", signification: "ma vie" },
     { arabe: "روحي", transliteration: "Rouhi", signification: "mon âme" },
     { arabe: "غاليتي", transliteration: "Ghalyti", signification: "ma précieuse" },
     { arabe: "زهرتي", transliteration: "Zahreti", signification: "ma fleur" },
     { arabe: "قمر", transliteration: "Qamar", signification: "mon étoile" },
     { arabe: "أميرة", transliteration: "Amira", signification: "princesse" },
     { arabe: "نور عيني", transliteration: "Noor 'Ayni", signification: "la lumière de mes yeux" },
     { arabe: "ملاكي", transliteration: "Malaki", signification: "mon ange" },
     { arabe: "دنيتي", transliteration: "Dunyati", signification: "mon monde" }
];

const hadiths = [
     "Le Messager d’Allah (paix et salut sur lui) a dit : « Les actions ne valent que par leurs intentions. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « Facilitez et ne rendez pas les choses difficiles, annoncez la bonne nouvelle et ne faites pas fuir les gens. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « Aucun de vous ne sera véritablement croyant tant qu’il n’aimera pas pour son frère ce qu’il aime pour lui-même. » (Boukhari et Mouslim)",
     "Le Messager d’Allah (paix et salut sur lui) a dit : « La meilleure des actions est celle qui est constante même si elle est petite. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « Celui qui croit en Allah et au Jour dernier doit dire du bien ou se taire. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La richesse ne consiste pas en l'abondance des biens mais la véritable richesse est celle de l'âme. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « Sourire à ton frère est une aumône. » (Tirmidhi)",
     "Le Prophète (paix et salut sur lui) a dit : « Le meilleur parmi vous est celui qui est le meilleur envers sa famille. » (Tirmidhi)",
     "Le Prophète (paix et salut sur lui) a dit : « Celui qui montre la voie du bien est comme celui qui le fait. » (Tirmidhi)",
     "Le Prophète (paix et salut sur lui) a dit : « Les meilleurs des hommes sont ceux qui sont les plus utiles aux autres. » (Darimi)",
     "Le Prophète (paix et salut sur lui) a dit : « Allah ne regarde ni vos corps ni vos apparences mais Il regarde vos cœurs et vos actions. » (Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « Celui qui est privé de douceur est privé de tout bien. » (Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « Celui qui ne remercie pas les gens n’aura pas remercié Allah. » (Tirmidhi)",
     "Le Prophète (paix et salut sur lui) a dit : « La foi comporte plus de soixante-dix branches, la plus élevée est la parole : ‘La ilaha illallah’ (Il n’y a de dieu qu’Allah) et la plus basse est de retirer un obstacle de la route. » (Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « Celui qui veut que sa subsistance soit accrue et que son terme soit prolongé, qu’il maintienne les liens de parenté. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « Le fort n’est pas celui qui renverse les autres par sa force. Le fort est celui qui se maîtrise dans la colère. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « Ne vous enviez pas, ne vous haïssez pas, ne vous détournez pas les uns des autres et soyez, ô serviteurs d'Allah, frères. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « Le musulman est le frère du musulman. Il ne l’opprime pas, ne le trahit pas et ne le méprise pas. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure aumône est celle faite durant le mois de Ramadan. » (Tirmidhi)",
     "Le Prophète (paix et salut sur lui) a dit : « Allah est miséricordieux envers celui qui est clément envers les autres. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La foi est la patience et la tolérance. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « Le croyant ne se lasse pas de faire du bien tant qu'il est en vie. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « Un sourire sincère est une aumône. » (Tirmidhi)",
     "Le Prophète (paix et salut sur lui) a dit : « La pureté est la moitié de la foi. » (Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « Celui qui appelle au bien aura une récompense semblable à celle de celui qui le fait. » (Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des richesses est une langue qui se souvient d'Allah. » (Tirmidhi)",
     "Le Prophète (paix et salut sur lui) a dit : « Les meilleures paroles sont celles qui sont brèves et concises. » (Tirmidhi)",
     "Le Prophète (paix et salut sur lui) a dit : « Le paradis est entouré de choses désagréables et l'enfer est entouré de convoitises. » (Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La clé du paradis est la prière. » (Ahmad)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est la prière à son temps. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est celle que l'on fait avec constance. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La foi est le bon comportement. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure aumône est celle faite à un parent pauvre. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure aumône est celle faite en secret. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure prière après les prières obligatoires est la prière de la nuit. » (Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « Le jeûne est un bouclier. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure aumône est celle qui est faite avec l'excédent de ses besoins. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de nourrir l'affamé. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est d'abreuver l'assoiffé. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de vêtir l'indigent. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est d'enseigner la science. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de construire une mosquée. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de rendre visite au malade. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de libérer un esclave. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est d'enterrer les morts. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de prêter de l'argent à un frère en difficulté. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de rendre visite à un parent éloigné. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de consoler celui qui est en deuil. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est d'aider une veuve. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de subvenir aux besoins d'un orphelin. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de donner à boire à celui qui a soif. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de répondre à une demande de secours. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de préserver la chasteté. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de préserver la langue. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de parler doucement. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de donner des conseils. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de pardonner. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de réconcilier les gens. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de respecter les promesses. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de rendre visite à un voisin. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de rendre service à un voisin. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de prêter assistance à un voisin. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de s'abstenir de ce qui est interdit. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de rechercher la science. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de s'entraider dans le bien. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de s'abstenir de ce qui est douteux. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de se lever la nuit pour prier. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de demander pardon. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de faire des invocations. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de rappeler Allah. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de dire la vérité. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de se repentir. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de respecter les parents. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de subvenir aux besoins de la famille. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de bien se comporter envers les voisins. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de rendre visite à un malade. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de prêter attention aux enfants. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de subvenir aux besoins des parents. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de subvenir aux besoins des orphelins. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de respecter les promesses. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de respecter les engagements. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de se contenter de peu. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de remercier Allah. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de se repentir à Allah. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de se rappeler d'Allah. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de demander pardon à Allah. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de faire l'aumône en secret. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de se lever la nuit pour prier. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de se contenter de ce qu'Allah a donné. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de se rappeler d'Allah en tout temps. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de remercier Allah pour Ses bienfaits. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de se repentir à Allah pour ses péchés. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de se rappeler d'Allah dans toutes ses actions. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de remercier Allah pour chaque instant de sa vie. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de se rappeler d'Allah dans chaque situation. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de remercier Allah pour chaque bienfait. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de se repentir à Allah pour chaque péché. » (Boukhari et Mouslim)",
     "Le Prophète (paix et salut sur lui) a dit : « La meilleure des œuvres est de se rappeler d'Allah en tout lieu. » (Boukhari et Mouslim)"
];

const trackedContacts = ['221762773266@c.us', '221782621023@c.us', '221775858605@c.us'];

module.exports = { surnoms, hadiths, trackedContacts };